name: Build & Release SoloAlert

on:
  push:
    branches:
      - main

jobs:
  build:
    name: Build SoloAlert
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install Dependencies
        run: npm ci

      - name: Build Project (Minify JS & CSS)
        run: npm run build

      - name: Commit & Push dist/
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add dist/
          git commit -m "🤖 Auto-build: Minified dist/ updated [skip ci]" || echo "No changes"
          git push origin main
